[package]
name = "pantheon-probe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
figlet-rs = "0.1.5"
futures = "0.3.29"
indicatif = "0.15"
reqwest = {version = "0.11.22"}
semver = "1.0.20"
tokio = {version = "1.33.0", features =["full"]}
