[package]
name = "pantheon-probe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.22"}
tokio = {version = "1.33.0", features =["full"]}
